.gitattributes
Taken from accessibility-insights-web's config
=> Add .gitignore file enforcing line endings

src/axe-extension.ts
Removes the axe extensions that were only there for `axe-utils` benefit now that `axe-utils` is removed.
=> remove axe typings that were only required by axe-utils

package-lock.json, package.json, src/index.ts
Type `SarifLog` is not exported from index.ts, meaning code example in README.md won't build.
```
error TS2305: Module '"node_modules/axe-sarif-converter/dist/index"' has no
exported member 'SarifLog'.
import { convertAxeToSarif, SarifLog } from 'axe-sarif-converter';
```
To make it build, `SarifLog` needs to be exported from package level (index.ts).
(Also fixed version in package-lock.json)
=> Export SarifLog from index.ts

package-lock.json
Fixes 3 high-vulnerability audit warnings from `npm run audit`.
Used `npm run audit-fix`
=> remove audit warning by running npm audit fix

.github/pull_request_template.md, README.md, azure-pipelines.yml, package-lock.json, package.json
*(note: this PR sets up semantic-release with `--dry-run`, so we can double check what it thinks it would do in the real build/release environment. There will be a second separate PR removing --dry-run)*
Sets up [semantic-release](https://github.com/semantic-release/semantic-release) in its default configuration, which will run the following steps on every merge into master (after all the normal CI checks have passed only):
* Look for the most recent "vX.Y.Z" tag in the repo
* Look at all the merge commits to master since that point
* If any contain `fix:` or `feat:` work, start a new release
* Parse the commit messages as [Conventional Commits](https://www.conventionalcommits.org) to form release notes
* Use `fix:`/`feat:`/`BREAKING CHANGE:` info in the merge commits to determine the …
=> feat: set up continuous deployment from master with semantic-release

package.json
Excludes the test-results folder from the licence check. This used to slip under the radar, but the recent addition of npm test in npm precheckin means that npm precheckin now fails spuriously without this change.
I also alphabetized the list while I was here.
=> chore: add test-results to license check exclusion list

azure-pipelines.yml
Per [Pipelines docs](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#secret-variables), secret pipeline variables are not automatically propagated to env variables like non-secret variables are. This explicitly forwards the secret variables that semantic-release needs as environment variables.
=> chore: propagate secret env vars to semantic release

yarn.lock
This is the result of running `yarn upgrade`. It fixes the assorted `yarn audit` failure in ... -> node-tar paths
Fixes #37
=> chore: run yarn upgrade, fixes all yarn audit issues

.github/CODEOWNERS
Updated casing from "Microsoft" to "microsoft" to match the updated casing of the microsoft github org.
=> chore: update casing for microsoft in code owners file

README.md
If you use the README's usage sample as-is in Node LTS, you'll get a warning about use of an experimental node API. This change updates the example to avoid the warning.
=> fix: update README example to avoid using experimental fs.promises

src/axe-tool-property-provider-21.test.ts, src/axe-tool-property-provider-21.ts, src/constants.ts, src/wcag-taxonomy-provider.test.ts, src/wcag-taxonomy-provider.ts
- Moved GUID to exported constant in `wcag-taxonomy-provider.ts`
- Updated `axe-tool-property-provider` and `wcag-taxonomy-provider` files and tests to use GUID from `wcag-taxonomy-provider.ts`
=> refactor: exported guid constant from wcag-taxonomy-provider

src/axe-tool-property-provider-21.test.ts, src/axe-tool-property-provider-21.ts, src/result-to-rule-converter.test.ts, src/result-to-rule-converter.ts, src/sarif-converter-21.test.ts, src/sarif-converter-21.ts, src/wcag-taxonomy-provider.test.ts, src/wcag-taxonomy-provider.ts
- Moved `driver` property from axe-tool-property-provider to `sarif-converter-21` so it's easier to add rules to axe tool property
- Moved functions for converting results to rules from `sarif-converter-21` to new class `ResultToRuleConverter` (will remove `ResultDecorator` in future PR)
- Added function to format rules in `rulesDictionary` to relationships
- Added unit tests for `ResultToRuleConverter`
- Added rules to axe tool properties in `sarif-converter-21`
- Moved WCAG taxonomy reference data and getter to `wcag-taxonomy-provider` and added relevant unit test
=> process rules from results for axe tool properties

src/artifact-property-provider.test.ts, src/artifact-property-provider.ts, src/result-to-rule-converter.test.ts, src/result-to-rule-converter.ts, src/sarif-converter-21.ts, src/sarif/custom-sarif-types-21.ts, src/test-resources/basic-axe-v3.2.2-reporter-v2.json, src/test-resources/basic-axe-v3.2.2-sarif-v2.1.2.sarif
- Modified `sarif-converter-21.ts` to output axe results to sarif v2.1.2 results
- Removed `description` property from `artifact-property-provider.ts` and `basic-axe-v3.2.2-sarif-v2.1.2.sarif` because target page title is unspecified in axe results
- Changed `targetPageUrl` to `url` in `basic-axe-v3.2.2-reporter-v2.json` because `targetPageUrl` is used only in `DecoratedAxeResults`
- Removed unused `partialFingerprints` and `properties` from `sarif-converter-21.ts`
- Updated `custom-sarif-types-21.ts` Result `kind` and `level` enums to match Sarif types and removed custom `Message` type
- Removed references to `custom-sarif-types-21.ts` in `sarif-converter-21.ts` (will remove `custom-sarif-types-21.ts` completely after `axe-raw-sarif-converter` support for sarif v2.1.2 is done)
- …
=> convert axe results to sarif results

src/axe-raw-sarif-converter-21.test.ts, src/axe-raw-sarif-converter-21.ts
- Copied `axe-raw-sarif-converter.ts` and `axe-raw-sarif-converter.test.ts` to `axe-raw-sarif-converter-21.ts` and `axe-raw-sarif-converter-21.test.ts`, respectively, to make comparing changes for the updated axe raw to sarif v2.1.2 converter easier to see/review. The old axe-raw-sarif-converter files will be removed and these files will be renamed to exclude `-21` once implementation is complete.
=> chore: copied axe-raw-sarif-converter to axe-raw-sarif-converter-21

src/axe-raw-sarif-converter-21.test.ts, src/axe-raw-sarif-converter-21.ts, src/test-resources/basic-axe-v3.2.2-reporter-raw.json
*Note: This is work in progress. There are some blocks of code commented out that will be uncommented as they are updated to support sarif v2.1.2. The integration test in `axe-raw-sarif-converter-21.test.ts` will be skipped until conversion to new sarif version is done.*
- Updated sarif version and corresponding types in `axe-raw-sarif-converter-21.ts`
- Removed `custom-sarif-types` import from `axe-raw-sarif-converter-21.ts`
- Changed message in `basic-axe-v3.2.2-reporter-raw.json` to match message in `basic-axe-v3.2.2-sarif-v2.1.2.sarif`
- Added `converter-property-provider`, `artifact-property-provider`, and `wcag-taxonomy-provider` to `axe-raw-sarif-converter-21.ts` and corresponding test
- Removed `properties` from sarif `run` output
=> chore: update axe raw sarif converter to output sarif v2.1.2 part 1

src/__snapshots__/index.test.ts.snap, src/axe-raw-result.ts, src/axe-raw-sarif-converter-21.test.ts, src/axe-raw-sarif-converter-21.ts, src/index.test.ts
- Added `xpath` to `axe-raw-results.ts` typings file
- Modified format of sarif results output to match sarif v2.1.2 in `axe-raw-sarif-converter-21.ts`
- Added tests to `index.test.ts` with fixed `environmentData` to match environment data in sample sarif output (`basic-axe-v3.2.2-sarif-v2.1.2.sarif`)
- [] PR title respects [Conventional Commits](https://www.conventionalcommits.org) (starts with `fix:`, `feat:`, etc, and is suitable for user-facing release notes)
=> chore: output sarif results from axe raw results

src/axe-raw-sarif-converter-21.ts, src/sarif-converter-21.ts, src/sarif-result-message-formatter.test.ts, src/sarif-result-message-formatter.ts
- Moved message formatting functions to new file `sarif-result-message-formatter.ts` because they are common to `sarif-converter-21` and `axe-raw-sarif-converter-21`
- Added tests for `sarif-result-message-formatter`
=> refactor: move message formatter to new file

src/__snapshots__/index.test.ts.snap, src/converter-property-provider.test.ts, src/converter-property-provider.ts, src/test-resources/basic-axe-v3.2.2-sarif-v2.1.2.sarif
- Updated `converter-property-provider` to automatically populate version number from `package.json`
- Updated snapshot and `basic-axe-v3.2.2-sarif-v2.1.2.sarif` sample output accordingly
=> chore: get converter version from package json

src/axe-raw-sarif-converter-21.test.ts
- Added skipped integration test back in after fixing sarif normalization for new sarif format (remove second logicalLocation from all results if it is present because axe results by default **will not** have that logicalLocation, while axe raw results **will** have it by default)
=> test: re-add integration test for axe-raw-sarif-converter

src/__snapshots__/index.test.ts.snap, src/axe-raw-sarif-converter-21.ts, src/sarif-converter-21.ts
- Added period to end of result `message` text for results without nodes to comply with sarif schema
- Updated relevant snapshot
=> chore: add period to end of message for results without nodes

README.md
Adds a "Version numbers" section to the README that describes the mappings between axe-sarif-converter version and axe-core/SARIF format versions.
=> chore: add version mapping info to readme

wallaby.conf.js
We never updated our wallaby configuration to understand our `/src/test-resources` folder, so there were false failures from wallaby in tests that read from them. This fixes those false failures.
=> chore: fix wallaby config to enable tests that use test-resources files

package.json
Previously, we set an engine requirement of `"yarn": "^1.15.1"`, which forced prospective consumers to use pretty recent yarn versions in their consuming projects even though we don't actually need any recent yarn features. We aren't doing anything special in our package.json; we don't need to require *any* single specific package manager (npm, yarn, etc are fine to consume the project with), so this just removes the package manager engine requirement outright.
=> fix: remove the recent yarn engine requirement

package.json, yarn.lock
Bumps all devDependencies up to latest versions. Leaving bumps of non-dev-dependencies `@types/sarif` and `axe-core` for a separate PR since they'll require test updates to check for input format changes.
(This should be a `chore:` and not a `fix:`, but I used the wrong tag in the last fix: PR's merge commit [the GitHub behavior where it doesn't use the PR title for the merge commit title if there's only one commit in the PR strikes again], so using fix here to artifically force a semantic-release that includes #71 )
=> fix: upgrade to lastest versions of devDependencies

package.json, yarn.lock
@types/sarif received a non-breaking update with 2.1.1 -> 2.1.2. This widens the range this library claims support for to include both versions.
It continues to use a strict upper bound rather than a caret version, since the SARIF standard and correspondingly @types/sarif have historically been willing to make breaking changes in patch versions (eg, from 2.1.0 -> 2.1.1).
=> fix: widen @types/sarif dependency to accept both 2.1.1 and 2.1.2

.github/CODEOWNERS
We've started updating all the accessibility insights repos to use a shared CODEOWNERS team, rather than maintaining separate ones per project. This brings axe-sarif-converter up to date with this new policy.
- [n/a] Ran `yarn precheckin`
=> chore: generalize CODEOWNERS to use whole-team instead of web-specific team

README.md, azure-pipelines.yml, jest.config.js, package.json, src/__snapshots__/cli.test.ts.snap, src/cli.test.ts, src/cli.ts, src/test-resources/axe-cli-v3.1.1.json, yarn.lock
Adds an `axe-sarif-converter` CLI tool to wrap the library and associated acceptance tests. Proposed usage:
```
> axe-sarif-converter --help
axe-sarif-converter: Converts JSON files containing axe-core Result object(s)
into SARIF files
Options:
--help             Show help                                         [boolean]
--version          Show version number                               [boolean]
--input-files, -i  Input JSON file(s) containing axe-core Result object(s).
Does not support globs. Each input file may consist of
either a single root-level axe-core Results object or a
root-level array of axe-core Results objects.
[array] [required]
--output-file, -o  Output SARIF file. Multiple input files (or input files
containing multiple Result objects) will be combined into
one output …
```
=> feat: add command line interface

package.json, src/test-resources/generator/package.json, src/test-resources/generator/yarn.lock, yarn.lock
Update kind-of package to ^6.0.3, minimist to ^1.2.2 and acron to ^7.1.1 using yarn resolutions to fix Github security alert
for info about yarn selective dependency resolutions: https://classic.yarnpkg.com/en/docs/selective-version-resolutions/
=> chore: Update kind-of, minimist and acron packages

README.md, package.json, src/__snapshots__/index.test.ts.snap, src/cli.test.ts, src/index.test.ts, src/test-resources/basic-axe-v4.0.1.axe-cli-v3.2.0.json, src/test-resources/basic-axe-v4.0.1.reporter-raw.json, src/test-resources/basic-axe-v4.0.1.reporter-v1.json, src/test-resources/basic-axe-v4.0.1.reporter-v2.json, src/test-resources/basic-axe-v4.0.1.sarif, src/test-resources/generator/package.json, src/test-resources/generator/yarn.lock, src/test-resources/w3citylights-axe-v4.0.1.axe-cli-v3.2.0.json, src/test-resources/w3citylights-axe-v4.0.1.reporter-raw.json, src/test-resources/w3citylights-axe-v4.0.1.reporter-v1.json, src/test-resources/w3citylights-axe-v4.0.1.reporter-v2.json, src/test-resources/w3citylights-axe-v4.0.1.sarif, yarn.lock
Update axe-core from 3.5.5 to 4.0.1, following the directions from the readme
=> feat(axe-core-4.0.1): bump axe-core from 3.5.5 to 4.0.1

azure-pipelines.yml
Previously, the release build for the package was using its own copy of GH_TOKEN and NPM_TOKEN specified as secret variables on the private release build pipeline. This updates them to instead use the variables from the KeyVault-backed variable group, to make rotating the secrets easier in the future.
=> chore: have release builds use secrets from KeyVault rather than pipeline variables

.vscode/launch.json
Adapted from https://github.com/microsoft/accessibility-insights-web/blob/master/.vscode/launch.json
=> chore: add VSCode launch profile for debugging tests

package.json, yarn.lock
The security vulnerability is described here: https://github.com/microsoft/axe-sarif-converter/network/alert/yarn.lock/yargs-parser/open
The change was to call
- yarn remove semantic-release
- yarn add --dev semantic-release
=> Chore: Update yargs-parser due to a security update

README.md, src/cli.ts, src/test-resources/generator/generate-axe-cli-resources.ts, src/test-resources/generator/generate-axe-core-resources.ts, src/test-resources/generator/package.json, src/test-resources/generator/yarn.lock
This updates all the test-resources/generator dependencies (which dependabot doesn't cover on its own), including migrating the usages of axe-cli and axe-puppeteer to @axe-core/cli and @axe-core/puppeteer
Normally I'd prefer to keep the update to axe-cli pinned with adding the new generated test cases for it, but there were enough notable changes without doing that that I decided to keep that separate/for a later and more mechanical review.
This is sort-of user facing in that it involves user-facing doc changes; using a chore tag to bundle the feat update into one combined change that also handles updating the root dependency to axe-core 4.0.2 (next PR)
=> chore(axe-core-4.0.2): update test generator deps (including new axe integration packages)

src/__snapshots__/index.test.ts.snap, src/axe-raw-sarif-converter.ts, src/sarif-converter.ts, src/test-resources/basic-axe-v3.2.2.sarif, src/test-resources/basic-axe-v3.3.2.sarif, src/test-resources/basic-axe-v3.4.1.sarif, src/test-resources/basic-axe-v3.4.2.sarif, src/test-resources/basic-axe-v3.5.1.sarif, src/test-resources/basic-axe-v3.5.2.sarif, src/test-resources/basic-axe-v3.5.3.sarif, src/test-resources/basic-axe-v3.5.4.sarif, src/test-resources/basic-axe-v3.5.5.sarif, src/test-resources/basic-axe-v4.0.1.sarif, src/test-resources/basic-axe-v4.0.2.sarif, src/test-resources/w3citylights-axe-v3.2.2.sarif, src/test-resources/w3citylights-axe-v3.3.2.sarif, src/test-resources/w3citylights-axe-v3.4.1.sarif, src/test-resources/w3citylights-axe-v3.4.2.sarif, src/test-resources/w3citylights-axe-v3.5.1.sarif, src/test-resources/w3citylights-axe-v3.5.2.sarif, src/test-resources/w3citylights-axe-v3.5.3.sarif, src/test-resources/w3citylights-axe-v3.5.4.sarif, src/test-resources/w3citylights-axe-v3.5.5.sarif, src/test-resources/w3citylights-axe-v4.0.1.sarif, src/test-resources/w3citylights-axe-v4.0.2.sarif
Add's a $schema value to the outputted Sarif file. 
Some places, in particular GitHub [require a $schema field to be populated](https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/sarif-support-for-code-scanning#sariflog-object)
This code adds that schema url using the value from the spec. Tests have been updated to include the field.
I have validated that this change is inline with the [Sarif spec](https://docs.oasis-open.org/sarif/sarif/v2.1.0/os/sarif-v2.1.0-os.html#_Toc34317481) 
> A sarifLog object MAY contain a property named $schema whose value is a string containing an absolute URI from which a JSON schema document [JSCHEMA01] describing the version of the SARIF format to which this log file conforms can be obtained. …
=> feat: add $schema to outputted files

.dependabot/config.yml
This PR adds a config file for dependabot that enables the test-resource generator for updates and configures the tags/prefixes/etc to match what we use in other repos.
=> chore: add dependabot config file

src/test-resources/generator/package.json, src/test-resources/generator/yarn.lock
- Updated chromedriver@latest to use axios 0.21.1 to resolve CVE-2020-28168
=> fix: update latest chromedriver version to use axios 0.21.1 for security fix

.releaserc.json
`semantic-release` understands to treat `master` as a release branch by default, but not `main` (see https://github.com/semantic-release/semantic-release/issues/1581). This PR explicitly configures semantic-release to release out of `main`.
Fix our release process.
Followup to #602
I verified locally with `yarn semantic-release --dry-run` that semantic-release does seem to be picking up the new configuration
=> chore: configure semantic-release to use the main branch as our release branch

package.json, yarn.lock
Dependabot cannot update ssri to a non-vulnerable version
The latest possible version that can be installed is 6.0.1 because of the following conflicting dependencies:
semantic-release@17.4.2 requires ssri@^6.0.1 via a transitive dependency on cacache@12.0.4
semantic-release@17.4.2 requires ssri@^6.0.0 via a transitive dependency on make-fetch-happen@5.0.2
semantic-release@17.4.2 requires ssri@^6.0.1 via a transitive dependency on pacote@9.5.12
semantic-release@17.4.2 requires ssri@^6.0.1 via a transitive dependency on libnpmpublish@1.1.3
semantic-release@17.4.2 requires ssri@^6.0.1 via a transitive dependency on npm@6.14.8
The earliest fixed version is 8.0.1.
Avoid security vulnerabilities.
=> fix: Update ssri to a non vulnerable version

.github/renovate-self-host-config.json5, .github/renovate.json5, .github/workflows/renovate.yml
This PR is an initial attempt to trial using [Renovate](https://docs.renovatebot.com/) instead of Dependabot for automated dependency updates.
This PR uses renovate/github-action to implement a self-hosted Renovate configuration. At a high level, this works by using a GitHub workflow that runs on a schedule every 15 minutes to run a "renovate" command, which queries for any new dependency updates and creates/updates/merges any required dependency update PRs.
For the purposes of the trial experiment, this workflow is currently set up just in this local repo. If we like how this works in `axe-sarif-converter`, I think the better long-term solution would be to create a separate `microsoft/accessibility-insights-renovate-config` repo to contain a single common worker workflow + config preset, …
=> chore: try out Renovate instead of Dependabot for dependency updates

.github/workflows/renovate.yml
Minor fixes after first attempt to trigger the new renovate action failed. Specifically:
* The `cron` trigger didn't work as expected at 5:15pm EST. Trying out switching the non-standard `MON-FRI` syntax with `1-5` to see if that improves the situation
* Documented how to use GitHub CLI to manually trigger the workflow
* Fixed incorrect pointer to `renovatebot/github-action`
See #685 
See #685 
=> chore: incremental fixes to experimental Renovate workflow

.github/workflows/renovate.yml
* Fixes the path to the self-host-config file to be relative to the repo root, rather than assuming it's under `/`
See #685
See #685
=> chore: incremental fixes to experimental Renovate workflow (part 2)

package.json, yarn.lock
Updates semantic-release and its dependencies to 17.4.7 (particularly, updates transitive dependency json-schema to resolve a security warning).
I noticed while I was here that `semantic-release` no longer has a transitive dependency on `lock-verify`, so I removed the accordingly-obsolete yarn resolution too.
Resolves (noisy) security warning
n/a
=> chore(deps): update semantic-release to 17.4.7

.github/dependabot.yml
This PR makes a no-op change to dependabot.yml to force Dependabot to re-evaluate the config file.
This is an attempt to work around an issue where, currently, Dependabot isn't processing non-security updates for this repo. The proximate cause is visible under the `Insights > Dependency Graph > Dependabot` GitHub UI for this repo, which shows this error:
```
The property '#/updates/1/ignore/0/versions' includes a duplicate. Ignores must have a unique combination of 'dependency-name' and 'versions'
The property '#/updates/1/ignore/2/versions' includes a duplicate. Ignores must have a unique combination of 'dependency-name' and 'versions'
```
I think this is a bogus error (the "duplicates" are in a different `updates` item, not the same item), so I'm starting by trying to see if Dependabot …
=> chore(deps): re-enable dependabot

azure-pipelines.yml
`semantic-release@18.0.0` includes a breaking change that requires node >= 14.17.0. This bumps our CI environment to the latest v14 node version to unblock #697 
Unblocks other dep updates
n/a
=> chore(deps-dev): bump version of node used for CI to 14.18.3

src/test-resources/generator/package.json, src/test-resources/generator/yarn.lock
This PR updates to latest puppeteer/chromedriver/etc in our test resource generator.
It also enables us to remove both of the resolutions in the generator - they're both included by default with the updates.
Primarily motivated by wanting to resolve a dependabot alert for an old `node-fetch` that the old puppeteer version depended on.
n/a
=> chore(deps-dev): update test case generator puppeteer deps

.prettierignore, SECURITY.md
We are adding the latest version of the SECURITY.md file as found here: https://github.com/microsoft/repo-templates/blob/main/shared/SECURITY.md.
After checking with the Github in Microsoft (GiM) team, we are being asked to add this file to all of our open-source repos. This file is used to help the community understand the Microsoft open source security policy and how to safely report security issues. GitHub uses the presence of this file to light-up security reminders and a link to the file. More information for internal reference can be found here: https://aka.ms/opensource
Ensures compliance with GiM/Open Source policy preferences
=> chore: Adding required SECURITY.md file to the repo

package.json, yarn.lock
This PR removes several obsolete yarn resolutions (specifically, ones which were not actually resulting in forcibly upgrading the package they referenced).
In one instance, this fixed an issue where we were unintentionally *downgrading* the version of `acorn` being used in one dependency chain.
Reduce technical debt.
n/a
=> chore: clean up obsolete yarn resolutions

azure-pipelines.yml
As described at https://github.com/actions/virtual-environments/issues/6002, Ubuntu 18.04 is being phased out. This moves to Ubuntu 22.04, which is the current LTS version.
Use current versions
- [n/a] (if applicable) Addresses issue:
=> chore: Use newer Ubuntu LTS version

azure-pipelines.yml
CodeQL support is automatically injected into our CI builds but requires a variable to be set to enable analysis.
Security requirement.
=> chore: enable CodeQL analysis in CI builds

package.json
PR #897 updated `rimraf` from 3.0.2 to 4.0.4. Unfortunately, rimraf v4 [dropped support for globs](https://github.com/isaacs/rimraf#major-changes-from-v3-to-v4) which we were using in `yarn clean` to delete the `dist` and `test-results` folders, so that started erroring out. Since `yarn clean` is called by `yarn prebuild`, this broke running local builds. PR and CI builds were not affected. This change removes the use of globs.
Get local builds working again.
=> fix: repair local build break after rimraf v4 update

CONTRIBUTING.md, README.md
* Splits out CONTRIBUTING docs into their own file (with the CELA-required CLA and CoC notices repeated in both places).
* Expands the CONTRIBUTING docs to make it clear what's for external contributors vs just our team and to add documentation about how releases to NPM work
n/a
n/a
=> chore: expand and split out CONTRIBUTING documentation

.github/dependabot.yml
Dependabot for our repos is scheduled to run at fairly different times that are inconvenient for some geographies. This PR moves this repo's dependabot time to 08:30 UTC (14:00 IST, 01:30 PDT, 00:30 PST).
Part of [Feature 2083093](https://mseng.visualstudio.com/1ES/_queries/edit/2083093) (internal access required to view).
- [n/a] Ran `yarn precheckin`
=> Chore(oncall-vendor-transition): Move Dependabot to 08:30 UTC

package.json, yarn.lock
https://github.com/microsoft/axe-sarif-converter/security/dependabot/26 calls out a command injection vulnerability in `chromecriver` versions earlier than 119.0.1. This PR adds a resolution for `chromedriver` to force usage of the version with the fixed vulnerability.
Address https://github.com/microsoft/axe-sarif-converter/security/dependabot/26
=> chore: Fix vulnerability in chromedriver

README.md
This is updating the text in the README for the Usage section to now show "USAGE".
Triggering a build to confirm that the new GH token is being consumed properly 
Quarterly DRI rotation
=> fix: Change "Usage" heading in README to all caps

README.md
Returning back to standard format after trivial change in #1180. "USAGE" is now back to "Usage". Will sync with vendor team to see how migration is affecting token consumption
Part of quarterly rotation
=> chore(rotation): returning README to standard formatting/reverting trivial change

azure-pipelines.yml
1ES PT adds tags to pipeline runs using the access token provided by ADO. In the case of pipeline runs against forked repos of a GitHub repo, the access token does not have Edit build quality permissions and hence cannot add tags. To unblock those pipelines, skipped tagging by using the option SkipBuildTagsForGitHubPullRequests.
Verified that the only change in the pipeline run is that it do not add "1ES.PT.Unofficial" tag on the Run. In place of that it adds below warning message.
##[warning]1ES PT Warning: Skipping build tags as this build is a pull request form GitHub which does not have permissions to add tags.
- [na] PR contains no breaking changes, **OR** description of both PR **and final merge commit** starts with `BREAKING CHANGE:`
- [na] (if applicable) Addresses issue: #0000
- …
=> fix: Added skip setting for 1ES PT tag in PR pipeline

.github/pull_request_template.md
semantic-release uses PR title for deciding release version and it follows https://www.conventionalcommits.org/en/v1.0.0/. It is required to have terminal colon and space. So added this in PR checklist to verify PR title before merging it.
=> fix: update PR template for PR title naming convention.

package.json, src/__snapshots__/index.test.ts.snap, yarn.lock
Bumps [jest](https://github.com/jestjs/jest/tree/HEAD/packages/jest), [@types/jest](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/jest) and  [ts-jest](https://github.com/kulshekhar/ts-jest). These dependencies needed to be updated together.
Updates `jest` from 27.5.1 to 29.7.0
Updates `@types/jest` from 27.5.0 to 29.5.12
Updates `ts-jest` from 27.1.4 to 29.2.3.
Added `jest-environment-jsdom` 29.7.0, now it is not shipped with jest by default.
Updated index.test.ts.snap file
Dependabot PR
https://github.com/microsoft/axe-sarif-converter/pull/1336
https://github.com/microsoft/axe-sarif-converter/pull/1345
- [na] (if applicable) Addresses issue: #0000
- [na] Added relevant unit tests for your changes
=> chore(deps-dev): Bump jest from 27.0.3 to 29.7.0, @types/jest from 27.4.0 to 29.5.12 and Bump ts-jest from 27.1.4 to 29.2.3

package.json, pipelines/shared-template.yml
Node 16 left support in October 2023. The only known consumer of axe-sarif-converter is the accessibility-insights-service repo, which already uses Node 20.
Get on a supported version that we expect to last for a while
BREAKING CHANGE: Bump Node requirement to Node 20
=> BREAKING CHANGE: Update node version to 20.x
