microsoft/axe-sarif-converter

- .github/CODEOWNERS
Copies the CODEOWNERS file as is from accessibility-insights-web
> Set code owners for the repo to match AI4Web

- .prettierignore
- .vscode/settings.json
- package-lock.json
- package.json
- prettier.config.js
- tslint.json
Add Initial setup for 
- prettier
- tslint
- vscode automatic formatting & lint checking
- copyright header
> add initial setup for prettier and tslint

- .vscode/settings.json
- README.md
- package.json
- tslint.json
This is strictly the automatic changes from npm run format
> npm run format

- wallaby.conf.js
Implements a basic wallaby.conf.js
> Add Wallaby support

- package-lock.json
- package.json
- src/index.ts
- src/placeholder.test.ts
- src/placeholder.ts
* Adds an `npm run lint`
* Fixes pre-existing lint errors in placeholders
> Enable tslint

- .vscode/settings.json
Matches web PR https://github.com/Microsoft/accessibility-insights-web/pull/489
> Pin version of typescript used by vscode to package.json

- src/__snapshots__/result-decorator.test.ts.snap
- src/result-decorator.test.ts
- src/sarif-converter.test.ts
- src/string-utils.test.ts
This PR adds some unit tests to the files that we have in our code.
This is an ongoing process which will need more PRs but keeping it small and simple.
> [Tests] Add some unit tests

- src/environment-data-provider.test.ts
- src/environment-data-provider.ts
- src/index.test.ts
- src/index.ts
- src/sarif-converter.ts
- Added function to `environment-data-provider` to get environment data directly from the environment
- Created `sarifReporter` with callback to convert raw axe results to sarif
- Added relevant tests for `environment-data-provider` and `sarifReporter`
> feat: reporter that converts axe raw results to sarif log

- package-lock.json
- package.json
(give an overview. Add technical description describing your changes)
> chore: npm update in preparation for switch to yarn

- README.md
Add a Samples section with a link to [microsoft/axe-pipelines-samples](https://github.com/microsoft/axe-pipelines-samples) repo.
> chore: add a README section linking to axe-pipelines-samples

- src/__snapshots__/index.test.ts.snap
- src/axe-raw-sarif-converter-21.test.ts
- src/axe-raw-sarif-converter-21.ts
- src/sarif-converter-21.ts
(give an overview. Add technical description describing your changes)
> chore: add locations property for inapplicable nodes

- copyright-header.config.json
- package.json
- yarn.lock
Manually update to the new license-check-and-add that uses a separate config file rather than a blob in package.json
> chore(deps-dev): manually update to license-check-and-add 3.0.3

- azure-pipelines.yml
> chore: bump pipelines build agent and node versions to latest LTS values

- package.json
- yarn.lock
Upgrade minimist from 1.2.2 to 1.2.3
- [n/a] Ran `yarn precheckin`
> chore(deps): upgrade minimist to 1.2.3

- azure-pipelines.yml
> chore: update node version in CI/PR builds to latest LTS

- src/test-resources/generator/yarn.lock
bl has a security issue: updating to patched version.
> fix: update bl in lockfile

- azure-pipelines.yml
Node updated their LTS version to v14 yesterday; this bumps our builds to match the latest LTS. No change from a user's perspective (we continue to document downlevel node support)
> chore(deps-dev): update build to node 14

- README.md
(give an overview. Add technical description describing your changes)
> chore(rotation): minor README change to trigger semantic-release

- README.md
Minor update to README to also update @axe-core/puppeteer version when updating axe-core version
> docs(README): add @axe-core/puppeteer to axe-core version update instruction

- README.md
- azure-pipelines.yml
- src/test-resources/basic-axe-v4.0.1.axe-cli-v3.2.0.json
Updates all the points where we refer to our own default branch name to reflect recent rename
Align name with Microsoft/GitHub policy
The rename in GitHub has already occurred and I've already updated our assorted DevOps pipelines accordingly.
> chore: update refs to default branch from master to main
